

#pragma once
#include "NativeGameplayTags.h"

namespace SASGameplayTags
{
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(StateTree_Pawn_MoveOrder);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(StateTree_Worker_HarvestOrder);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(StateTree_Worker_TransitionToLogistics);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(StateTree_Worker_Logistics_Unassigned);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(StateTree_Worker_Logistics_DeliverItem_MoveToSource);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(StateTree_Worker_Logistics_DeliverItem_MoveToTarget);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(StateTree_Combat_AttackTarget);
}